# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: 0.10.3
          use-tool-cache: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: wasm-pack build --target web
      - name: Package build
        run: |
          touch build
          cd build
          mv ../ace-builds-1.5.0 .
          mv ../css .
          mv ../js .
          mv ../pkg .
          mv ../index.html .
          mv ../DOCUMENTATION.md .
          cd ..
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
